name = "Li2Irrationality"
version = "0.1.0"
defaultTargets = ["Solution"]

[leanOptions]
autoImplicit = false

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "c55e6e786f49471c72fbddbec5415808896aec1e"

[[lean_lib]]
name = "Li2Unified"

[[lean_lib]]
name = "Li2Half"

[[lean_lib]]
name = "Challenge"

[[lean_lib]]
name = "Solution"
